### ISSUE TITLE
build: accetto/ubuntu-vnc-xfce-firefox-g3

### ISSUE THREAD

**Issue by StoneyJackson** [HFOSSedu/KitClient#24]
## The Story

```
As a developer,
I want accetto/ubuntu-vnc-xfce-firefox-g3 cached/mirrored in ghcr.io/hfossedu
so that if anything happens accetto/ubuntu-vnc-xfce-firefox-g3 that would cause this
    project to break I would have a backup until I can find an alternative.
```

## Motivation

accetto/ubuntu-vnc-xfce-firefox-g3 has only two tags: latest and latest-plus. This is another reason we want to cache it. We can't pin to a version. We can pin to a sha256 ID; but if the author isn't keeping around older versioned tags, they are likely not keeping around older images. So pinning to a hash value won't help us if they remove the image we pin to.

## Ideal solution

Once a week, if accetto/ubuntu-vnc-xfce-firefox-g3 is different than our latest cached image, pull it and cache it. Tag the new one by date.

## Version numbers

When adopting a new version of accetto/ubuntu-vnc-xfce, we must assume that it will result in a breaking change for our clients (Kits). Why? Because any change to the UI by any software in accetto/ubuntu-vnc-xfce could be a breaking change.

So every time we adopt a new accetto/ubuntu-vnc-xfce, we will bump the major version of KitClient. This is a signal to Kits to test against the new KitClient before adopting it themselves.

**Comment by braughtg** [comment]
Also add git tab command completion.

**Comment by StoneyJackson** [comment]
Done.
