### ISSUE TITLE
Custom Bash prompt with Student Name

### ISSUE THREAD

**Issue by braughtg** [HFOSSedu/KitClient#31]
The first time a Terminal runs in KitClient it should prompt the student for a name.  This name should then be included in the Bash prompt.  This ensures that the student is identified in each of the screenshots that they take for the activities.  It is a simple mechanism that makes it difficult for a student to not do their own work.

Ideally the prompt will include both the current directory and the student's name.

**Comment by braughtg** [comment]
The following creates a prompt that displays the `$NAME` environment variable and the current working directory.

`PS1="\e[1;35m$NAME\e[m:\e[1;36m\w\e[m \$ "`

<img width="193" alt="image" src="https://user-images.githubusercontent.com/16962482/212404712-8fc5165d-ea75-4235-a364-b4e101fef2fc.png">

**Comment by braughtg** [comment]
Adding the following to `.bashrc` seems to do the trick:

```bash
if [ ! -f .kitclient/kituser.txt ] ; then
  while [ -z $KIT_USER_NAME ] ; do
    read -p "Please enter your name: " KIT_USER_NAME
  done
  echo $KIT_USER_NAME > .kitclient/kituser.txt
fi
KIT_USER_NAME=$(cat .kitclient/kituser.txt) 
export PS1="\e[1;35m$KIT_USER_NAME\e[m:\e[1;36m\w\e[m \$ "
```

**Comment by StoneyJackson** [comment]
Do we want to support git status information? (a git prompt?) If so, can we still use an off-the-shelf prompt, or would we have to roll our own?
